In [1]:
### How to create an Array??

In [2]:
from array import *

In [11]:
arr1 = array('i',[10,20,30,40,50,60])
arr2 = array('f',[2.5,3,4,5,6])
arr3 = array('d',[2.5,3.5,4.5,5.5,6.5])

In [12]:
print("arr1:",arr1)
print("arr2:",arr2)
print("arr3:",arr3)

arr1: array('i', [10, 20, 30, 40, 50, 60])
arr2: array('f', [2.5, 3.0, 4.0, 5.0, 6.0])
arr3: array('d', [2.5, 3.5, 4.5, 5.5, 6.5])


In [13]:
print(type(arr1))
print(type(arr2))
print(type(arr3))

<class 'array.array'>
<class 'array.array'>
<class 'array.array'>


## Insert Element in an Array

In [15]:
print(arr1)
print(arr2)

array('i', [10, 20, 30, 40, 50, 60])
array('f', [2.5, 3.0, 4.0, 5.0, 6.0])


In [16]:
arr1.insert(6,70)

In [17]:
arr1

array('i', [10, 20, 30, 40, 50, 60, 70])

In [18]:
arr1.insert(0,80)

In [19]:
arr1

array('i', [80, 10, 20, 30, 40, 50, 60, 70])

In [20]:
arr1.insert(3,90)

In [21]:
arr1

array('i', [80, 10, 20, 90, 30, 40, 50, 60, 70])

## Today's Topics
- Array Treversal
- Accessing the element in an array
- Searching an element in an array
- Deleteling an element  in an array

In [1]:
from array import *

In [2]:
arr1 = array('i',[10,20,30,40,50,60,70,80,90])
print(arr1)

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])


In [3]:
### TC - o(n), SC - o(1)
def treverse(arr):
    for i in arr: ## o(n)
        print(i)  ## o(1)

In [4]:
treverse(arr1)

10
20
30
40
50
60
70
80
90


In [5]:
print(arr1)

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])


In [6]:
### TC - o(1), SC - o(1)
def accessElement(arr, ind): ## arr1[ind]
    if ind >= len(arr):
        print("Element is not found in array.")
    else:
        print(arr[ind])

In [10]:
accessElement(arr1, 10)

Element is not found in array.


In [11]:
print(arr1)

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])


In [12]:
### TC - o(n), SC - o(1)
def searchArray(arr, val):
    for i in arr:
        if i == val:
            return arr.index(val)
    return "Element not found in array."

In [15]:
print(searchArray(arr1, 100))

Element not found in array.


In [16]:
print(arr1)

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])


In [20]:
### TC - o(n), SC - o(1)
arr1.remove(70)

In [21]:
print(arr1)

array('i', [10, 30, 40, 50, 60, 80, 90])


## Today's Topics
- Create 2D Array
- Insert values in 2D Array

In [1]:
import numpy as np

In [4]:
arr1 = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr1 = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
newarr1 = np.insert(arr1, 2, [[1,2,3]], axis=1)
print(newarr1)

[[10 20  1 30]
 [40 50  2 60]
 [70 80  3 90]]


In [18]:
arr1 = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [20]:
newArr1 = np.append(arr1, [[1,2,3]], axis=0)
print(newArr1)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 1  2  3]]


### Accessing Elements in 2D Array

In [4]:
import numpy as np

In [5]:
arr1 = np.array([[10,20,30,40],[11,12,13,14],[21,22,23,24]])
print(arr1)

[[10 20 30 40]
 [11 12 13 14]
 [21 22 23 24]]


In [7]:
arr1[1][1]

12

In [8]:
def accessElement(arr, row, col):               
    if row >= len(arr) or col >= len(arr[0]): ### O(1)
        print('Invalid Index') ### O(1)
    else:
        print(arr[row][col]) ### O(1) TC - O(1) && SC - O(1)

In [12]:
print(arr1)
accessElement(arr1, row=2, col=3)

[[10 20 30 40]
 [11 12 13 14]
 [21 22 23 24]]
24


### Array Traversal - 2D Arrays

In [3]:
import numpy as np

In [4]:
arr1 = np.array([[10,20,30,40],[11,12,13,14],[21,22,23,24]])
print(arr1)

[[10 20 30 40]
 [11 12 13 14]
 [21 22 23 24]]


In [5]:
for i in range(len(arr1)):
    for j in range(len(arr1[0])):
        print(arr1[i][j])

10
20
30
40
11
12
13
14
21
22
23
24


In [6]:
def traverseArray(arr):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            print(arr1[i][j])

## ------------------> TC - O(n^2)
## ------------------> SC - O(1)

In [7]:
traverseArray(arr= arr1)

10
20
30
40
11
12
13
14
21
22
23
24


### Searching for an element in an 2D array

In [4]:
import numpy as np

In [5]:
arr1 = np.array([[10,20,30,40],[11,12,13,14],[21,22,23,24]])
print(arr1)

[[10 20 30 40]
 [11 12 13 14]
 [21 22 23 24]]


In [10]:
def searchElement(arr, value):
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            if arr[i][j] == value:
                return 'The value is located at index arr[' + str(i) + ']' +'[' + str(j) + '].'
    return 'Element not found, Invalid Value.'
## TC - O(mn)
## SC - O(1)

In [14]:
print(searchElement(arr1, 100))

Element not found, Invalid Value.


## Deleting Elements in 2D Array

In [13]:
import numpy as np

In [15]:
arr1 = np.array([[10,20,30,40],[11,12,13,14],[21,22,23,24]])
print(arr1)

[[10 20 30 40]
 [11 12 13 14]
 [21 22 23 24]]


In [19]:
newArr = np.delete(arr1, 3, axis=1)
print(newArr)

## TC - O(mn)
## SC - O(1)

[[10 20 30]
 [11 12 13]
 [21 22 23]]


## When to use/Avoid Arrays
### When to Use ??
- To store same type of data with multiple variables
- To access random elements.


### When to Avoid ??
- Different data types 
- Reserve Memory